"""
Automatic Code Writer - Opens apps and writes code
"""

import subprocess
import time
import pyautogui
import os

class CodeWriter:
    def __init__(self):
        self.code_templates = {
            "login page": '''<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <style>
        body { font-family: Arial; background: #f0f0f0; }
        .login-form { width: 300px; margin: 100px auto; padding: 20px; background: white; border-radius: 10px; }
        input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ddd; }
        button { width: 100%; padding: 10px; background: #007bff; color: white; border: none; cursor: pointer; }
    </style>
</head>
<body>
    <div class="login-form">
        <h2>Login</h2>
        <input type="text" placeholder="Username" id="username">
        <input type="password" placeholder="Password" id="password">
        <button onclick="login()">Login</button>
    </div>
    <script>
        function login() {
            const username = document.getElementById('username').value;
            const password = document.getElementById('password').value;
            if(username && password) {
                alert('Login successful!');
            } else {
                alert('Please fill all fields');
            }
        }
    </script>
</body>
</html>''',
            
            "calculator": '''def calculator():
    print("Simple Calculator")
    
    while True:
        try:
            num1 = float(input("Enter first number: "))
            operator = input("Enter operator (+, -, *, /): ")
            num2 = float(input("Enter second number: "))
            
            if operator == '+':
                result = num1 + num2
            elif operator == '-':
                result = num1 - num2
            elif operator == '*':
                result = num1 * num2
            elif operator == '/':
                result = num1 / num2 if num2 != 0 else "Cannot divide by zero"
            else:
                result = "Invalid operator"
            
            print(f"Result: {result}")
            
            if input("Continue? (y/n): ").lower() != 'y':
                break
                
        except ValueError:
            print("Invalid input!")

calculator()''',
            
            "todo app": '''import json

class TodoApp:
    def __init__(self):
        self.todos = []
    
    def add_todo(self, task):
        self.todos.append({'task': task, 'completed': False})
        print(f"Added: {task}")
    
    def show_todos(self):
        for i, todo in enumerate(self.todos, 1):
            status = "✓" if todo['completed'] else "○"
            print(f"{i}. {status} {todo['task']}")
    
    def complete_todo(self, index):
        if 1 <= index <= len(self.todos):
            self.todos[index-1]['completed'] = True
            print(f"Completed!")
    
    def run(self):
        while True:
            print("1. Add  2. Show  3. Complete  4. Exit")
            choice = input("Choose: ")
            
            if choice == '1':
                task = input("Task: ")
                self.add_todo(task)
            elif choice == '2':
                self.show_todos()
            elif choice == '3':
                index = int(input("Number: "))
                self.complete_todo(index)
            elif choice == '4':
                break

app = TodoApp()
app.run()'''
        }
    
    def open_app_and_write(self, app_name, code_content):
        """Open app and automatically type code"""
        try:
            # Open application
            if "notepad" in app_name.lower():
                subprocess.Popen(['notepad.exe'])
            elif "vscode" in app_name.lower() or "code" in app_name.lower():
                subprocess.Popen(['code'])
            else:
                subprocess.Popen(['notepad.exe'])
            
            # Wait for app to open
            time.sleep(2)
            
            # Type code automatically
            pyautogui.typewrite(code_content, interval=0.005)
            
            return True
            
        except Exception as e:
            print(f"Error: {e}")
            return False
    
    def write_code(self, request, app="notepad"):
        """Write code based on request"""
        request_lower = request.lower()
        
        # Find matching template
        for template_name, code in self.code_templates.items():
            if template_name in request_lower:
                print(f"Writing {template_name} code...")
                return self.open_app_and_write(app, code)
        
        # Default simple code
        simple_code = f'''# {request}
# Generated by JARVIS

def main():
    print("Hello from JARVIS!")
    # Your code here
    pass

if __name__ == "__main__":
    main()
'''
        print(f"Writing code for: {request}")
        return self.open_app_and_write(app, simple_code)

# Global instance
code_writer = CodeWriter()